### ISSUE TITLE
How to make document height adjust to height of only current tab?

### ISSUE THREAD

**Issue by lukehutch** [johnuberbacher/CSS-Tabs#4]
Your CSS-only tab library is awesome, thanks for posting it. However, if the content of each tab is of different heights, the height of the tallest tab content is used as the height for the entire tab collection, no matter which tab is visible.

Is it possible to make the height of the tab collection automatically adjust to the height of the current tab?

**Comment by lukehutch** [comment]
I figured it out -- the following line needs to be inserted into each `.tab__content`:

```css
.tab:checked:nth-of-type(1) ~ .tab__content:nth-of-type(1) {
	opacity: 1;
	-webkit-transition: 0.5s opacity ease-in, 0.2s transform ease;
	transition: 0.5s opacity ease-in, 0.2s transform ease;
	position: relative;
	top: 0;
	z-index: 100;
	-webkit-transform: translateY(0px);
		  transform: translateY(0px);
	text-shadow: 0 0 0;
        display: block;         /* <---- Insert this */
}
```

and the following into `.tab`:

```css
.tab__content {
	padding: 10px 25px;
	background-color: transparent;
	position: absolute;
	width: 100%;
	z-index: -1;
	opacity: 0;
	left: 0;
	-webkit-transform: translateY(-3px);
		  transform: translateY(-3px);
	border-radius: 6px;
        display: none;           /* <---- insert this */	
}
```
